[unstable]
#build-std-features = ["compiler_builtins-mem"]
build-std = ["core", "compiler_builtins"]


[build]
target = "x86_64_os.json"


[target.'cfg(target_os = "none")']
runner = "bootimage runner"